import 'package:get/get.dart';
import 'package:supabase_flutter/supabase_flutter.dart'; // Import Supabase

class AdminDeliveryFeeController extends GetxController {
  // Initialize Supabase client
  // Ensure you have initialized Supabase in your main.dart or elsewhere
  // Example: SupabaseClient supabase = SupabaseClient('YOUR_SUPABASE_URL', 'YOUR_SUPABASE_ANON_KEY');
  // For this example, we assume supabase is already initialized and accessible.
  // If not, you would need to pass it or initialize it here.
  // For simplicity, let's assume a global or accessible instance named 'supabase'.
  // In a real app, you'd likely inject this dependency.
  final SupabaseClient supabase =
      Supabase.instance.client; // Access the initialized client

  RxList<Map<String, dynamic>> deliveryFees = <Map<String, dynamic>>[].obs;

  @override
  void onInit() {
    super.onInit();
    fetchDeliveryFees();
  }

  Future<void> fetchDeliveryFees() async {
    try {
      // Fetch data from Supabase
      final response = await supabase
          .from('delivery_fees')
          .select('*'); // Select all columns

      // Supabase returns a List<Map<String, dynamic>> directly
      deliveryFees.value = List<Map<String, dynamic>>.from(response);

      // If your table has an 'id' column that is auto-generated by Supabase,
      // it will be included in the response. If not, you might need to map it.
      // For example, if your primary key is 'id':
      // deliveryFees.value = response.map((item) {
      //   return {
      //     'id': item['id'], // Assuming 'id' is the primary key column name in Supabase
      //     ...item,
      //   };
      // }).toList();
    } catch (e) {
      Get.snackbar('Error', 'Failed to fetch delivery fees: $e');
    }
  }

  Future<void> addDeliveryFee({
    required String admin_Division,
    String? admin_District,
    String? admin_Upazila,
    required double admin_fees,
  }) async {
    try {
      // Add data to Supabase
      await supabase.from('delivery_fees').insert({
        'admin_Division': admin_Division,
        'admin_District': admin_District,
        'admin_Upazila': admin_Upazila,
        'admin_fees': admin_fees,
      });
      fetchDeliveryFees(); // Refresh the list
      Get.snackbar('Success', 'Delivery fee added successfully!');
    } catch (e) {
      Get.snackbar('Error', 'Failed to add delivery fee: $e');
    }
  }

  Future<void> updateDeliveryFee({
    required String id, // Supabase uses primary key for updates/deletes
    required String admin_Division,
    String? admin_District,
    String? admin_Upazila,
    required double admin_fees,
  }) async {
    try {
      // Update data in Supabase
      await supabase.from('delivery_fees').update({
        'admin_Division': admin_Division,
        'admin_District': admin_District,
        'admin_Upazila': admin_Upazila,
        'admin_fees': admin_fees,
      }).eq('id', id); // Filter by the primary key 'id'
      fetchDeliveryFees(); // Refresh the list
      Get.snackbar('Success', 'Delivery fee updated successfully!');
    } catch (e) {
      Get.snackbar('Error', 'Failed to update delivery fee: $e');
    }
  }

  Future<void> deleteDeliveryFee(String id) async {
    try {
      // Delete data from Supabase
      await supabase
          .from('delivery_fees')
          .delete()
          .eq('id', id); // Filter by the primary key 'id'
      fetchDeliveryFees(); // Refresh the list
      Get.snackbar('Success', 'Delivery fee deleted successfully!');
    } catch (e) {
      Get.snackbar('Error', 'Failed to delete delivery fee: $e');
    }
  }
}
